Initial commit
Amsterdam/mijn-tips-api pull request #41
Opened 2021-06-15 09:08 UTC by MokumJ

- Waiting for the right image.
- Pending question for Marian about some of the logics

2021-06-15 09:26 UTC, drakonen requested changes

2021-06-15 09:26 UTC, drakonen commented on tips/api/tips_pool.json
> +    "datePublished": "2021-03-04",
```suggestion
    "datePublished": "2021-06-15",
```

2021-06-15 09:26 UTC, drakonen commented on tips/api/tips_pool.json
> +    "reason": "",
deze moet nog gevuld worden, en deze text moet ook langs de redactie

2021-06-15 09:26 UTC, drakonen commented on tips/api/tips_pool.json
> +    "imgUrl": "/api/tips/static/tip_images/stem.jpg"
dit plaatje moet nog veranderd worden.

2021-06-15 09:26 UTC, drakonen commented on tips/tests/test_tips.py
> +    def test_vakantie_verhuur(self):
dit kan nooit door flake8 heen gekomen zijn :)
hier moet een newline tusse van pep8

2021-06-15 11:36 UTC, timvanoostrom commented on tips/api/tips_pool.json
> +        "rule": "$.VERGUNNINGEN.*[@.caseType is 'B&B - vergunning'] and $.VERGUNNINGEN.*[@.decision is 'Verleend met overgangsrecht']"
Shouldn't this be `$.VERGUNNINGEN.*[@.caseType is 'B&B - vergunning' and @.decision is 'Verleend met overgangsrecht']` ?

2021-06-15 11:41 UTC, timvanoostrom commented on tips/api/tips_pool.json
> +        "rule": "$.VERGUNNINGEN.*[@.caseType is 'B&B - vergunning'] and $.VERGUNNINGEN.*[@.decision is 'Verleend met overgangsrecht']"
The rule now filters items with caseType=b&b and items with decision=verleend met overgangsrecht. 

In this case only b&b can have that decision but if there will ever be another vergunning with that kind of decision you will check this:

```
vergunningenBB = [ ... ]
vergunningenVerleendMetOvergangsRecht = [ ... ]

pass = vergunningenBB and vergunningenVerleendMetOvergangsRecht
```

Instead of

```
vergunningenBBVerleendMetOvergangsRecht = [ ... ]

pass = vergunningenBBVerleendMetOvergangsRecht
```

2021-06-15 14:06 UTC, timvanoostrom requested changes

2021-06-15 14:06 UTC, timvanoostrom commented on tips/tests/fixtures/fixture.py
> -            "VERGUNNINGEN": vergunningen,
Vergunningen is still relevant for other types of vergunningen. Are there any tips to related to that?

2021-06-15 14:06 UTC, timvanoostrom commented on tips/tests/test_tips.py
>              self.assertEqual(len(json), 1)
Maybe also assert the title of the tip? You don't really test if there is actually a tip in the result

2021-06-17 08:17 UTC, timvanoostrom approved these changes

2021-06-21 07:51 UTC, drakonen approved these changes

2021-06-21 08:33 UTC, drakonen commented on requirements.txt
> +urllib3==1.26.5
https://github.com/Amsterdam/mijn-tips-api/pull/40 deze is er ook al :)

2021-06-21 12:03 UTC, merged